name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [2.7, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.13.0'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: ./run_test.sh
  black:
    name: Check formatting with black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          pip3 install black
          black --check python/ test/
